version: '3'
volumes:
  dados:
networks:
  banco:
  web:
services:
  db:
    image: postgres:9.6
    environment:
      # POSTGRES_PASSWORD: example
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - dados:/var/lib/postgres/data
      - ./scripts:/scripts
      # padrao para inicializao de scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    # orquestra a inicializao, de forma a inicializar o app antes do frontend
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
    depends_on:
      - db